import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { CalculationResult, CategoryBreakdown } from "./carbonCalculations";

export interface PDFExportOptions {
  userName: string;
  calculations: CalculationResult;
  breakdown: CategoryBreakdown;
  date?: Date;
}

/**
 * Generate a PDF report for carbon offset calculations
 * @param options Export configuration
 */
export const generateOffsetReport = (options: PDFExportOptions) => {
  const doc = new jsPDF();
  const date = options.date || new Date();

  // Page configuration
  const pageWidth = 210; // A4 width in mm
  const pageHeight = 297; // A4 height in mm
  const margin = 20;

  // Add semi-transparent watermark
  doc.setGState({ opacity: 0.1 } as any);
  doc.setFontSize(60);
  doc.setTextColor(100, 100, 100);
  doc.text("1World1Nation", pageWidth / 2, pageHeight / 2, {
    align: "center",
    angle: 45,
  });
  doc.setGState({ opacity: 1.0 } as any);

  // Reset colors
  doc.setTextColor(0, 0, 0);

  // Header Section
  doc.setFontSize(24);
  doc.setFont("helvetica", "bold");
  doc.text("Carbon Offset Calculation Report", pageWidth / 2, 30, {
    align: "center",
  });

  // Subtitle
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(100, 100, 100);
  doc.text("Generated by 1World1Nation Carbon Offset Platform", pageWidth / 2, 38, {
    align: "center",
  });

  // User Info
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(11);
  doc.text(`Generated for: ${options.userName}`, margin, 55);
  doc.text(
    `Date: ${date.toLocaleDateString("en-US", {
      year: "numeric",
      month: "long",
      day: "numeric",
    })}`,
    margin,
    62
  );

  // Divider line
  doc.setDrawColor(22, 199, 132);
  doc.setLineWidth(0.5);
  doc.line(margin, 67, pageWidth - margin, 67);

  // Summary Box
  doc.setFillColor(22, 199, 132);
  doc.roundedRect(margin, 75, pageWidth - 2 * margin, 45, 3, 3, "F");

  // Summary Text
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text("Calculation Summary", margin + 5, 85);

  doc.setFontSize(12);
  doc.setFont("helvetica", "normal");
  doc.text(
    `Total CO2 Emissions: ${options.calculations.totalTonsCO2.toFixed(2)} tons`,
    margin + 5,
    95
  );
  doc.text(
    `Carbon Tokens Required: ${options.calculations.totalTokens} tokens`,
    margin + 5,
    103
  );
  doc.text(
    `Total Cost: $${options.calculations.totalCost.toFixed(2)}`,
    margin + 5,
    111
  );

  // Pricing info
  doc.setFontSize(9);
  doc.setFont("helvetica", "italic");
  doc.text("(1 token = 1 ton CO2 @ $1.20 per token)", margin + 5, 117);

  // Category Breakdown Section
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  doc.text("Category Breakdown", margin, 135);

  // Prepare table data
  const total = options.calculations.totalKgCO2;
  const categoryData = Object.entries(options.breakdown)
    .filter(([_, value]) => value > 0) // Only show categories with emissions
    .map(([category, value]) => {
      const percentage = total > 0 ? ((value / total) * 100).toFixed(1) : "0.0";
      const tons = (value / 1000).toFixed(3);
      return [
        category.charAt(0).toUpperCase() + category.slice(1),
        `${value.toFixed(2)} kg`,
        `${tons} tons`,
        `${percentage}%`,
      ];
    });

  // Add total row
  categoryData.push([
    "TOTAL",
    `${total.toFixed(2)} kg`,
    `${options.calculations.totalTonsCO2.toFixed(3)} tons`,
    "100%",
  ]);

  // Draw table
  autoTable(doc, {
    head: [["Category", "CO2 (kg)", "CO2 (tons)", "Percentage"]],
    body: categoryData,
    startY: 140,
    theme: "grid",
    headStyles: {
      fillColor: [22, 199, 132],
      textColor: [255, 255, 255],
      fontStyle: "bold",
      fontSize: 11,
    },
    bodyStyles: {
      fontSize: 10,
    },
    footStyles: {
      fillColor: [240, 240, 240],
      textColor: [0, 0, 0],
      fontStyle: "bold",
    },
    alternateRowStyles: {
      fillColor: [250, 250, 250],
    },
    columnStyles: {
      0: { fontStyle: "bold" },
      3: { halign: "right" },
    },
  });

  // Get final Y position after table
  const finalY = (doc as any).lastAutoTable.finalY + 15;

  // Information Box
  if (finalY < pageHeight - 60) {
    doc.setFillColor(235, 255, 234);
    doc.roundedRect(margin, finalY, pageWidth - 2 * margin, 30, 2, 2, "F");

    doc.setFontSize(10);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(0, 0, 0);
    doc.text("What's Next?", margin + 5, finalY + 8);

    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    const infoText = [
      "1. Purchase the required carbon tokens to offset your emissions",
      "2. Track your progress on your dashboard",
      "3. Receive a certificate upon completing your offset",
    ];

    infoText.forEach((text, index) => {
      doc.text(text, margin + 5, finalY + 16 + index * 6);
    });
  }

  // Footer
  doc.setFontSize(8);
  doc.setFont("helvetica", "italic");
  doc.setTextColor(128, 128, 128);
  const footerText = "This report is generated based on EPA and international carbon offset standards.";
  doc.text(footerText, pageWidth / 2, pageHeight - 15, { align: "center" });
  doc.text(
    "For more information, visit www.1world1nation.org",
    pageWidth / 2,
    pageHeight - 10,
    { align: "center" }
  );

  // Company Logo watermark text (small)
  doc.setFontSize(7);
  doc.text("© 1World1Nation", margin, pageHeight - 5);

  // Save the PDF
  const fileName = `carbon-offset-report-${date.toISOString().split("T")[0]}.pdf`;
  doc.save(fileName);
};
